import os
import sqlite3
from twitchio.ext import commands
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class PulseBot(commands.Bot):
    def __init__(self):
        super().__init__(
            token=os.getenv('TMI_TOKEN'),
            prefix=os.getenv('PREFIX'),
            initial_channels=[os.getenv('CHANNEL')]
        )

    async def event_ready(self):
        print(f'🤖 PulseBot Data Collector Online as {self.nick}')

    async def event_message(self, message):
        # Ignore bot's own messages to avoid data pollution
        if message.echo:
            return

        # LOGIC: Save event to SQLite Database
        try:
            conn = sqlite3.connect('pulse.db')
            c = conn.cursor()
            
            # Insert username and message (Timestamp is auto-generated by DB)
            c.execute("INSERT INTO chat_logs (username, message) VALUES (?, ?)", 
                      (message.author.name, message.content))
            
            conn.commit()
            conn.close()
            print(f"💾 Data Logged: {message.author.name}")
        except Exception as e:
            print(f"Database Error: {e}")

        # Allow commands to process
        await self.handle_commands(message)

    @commands.command(name='pulse')
    async def pulse_cmd(self, ctx):
        await ctx.send(f"@{ctx.author.name} The Real-Time Monitoring System is Active! 📈")

# Run the bot
if __name__ == "__main__":
    bot = PulseBot()
    bot.run()